# Absenteeism at Work

In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [44]:
a_at_w = pd.read_csv('Absenteeism_at_work.csv',sep=';')
a_at_w.head()

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0  11                  26                 7                3        1   
1  36                   0                 7                3        1   
2   3                  23                 7                4        1   
3   7                   7                 7                5        1   
4  11                  23                 7                5        1   

   Transportation expense  Distance from Residence to Work  Service time  Age  \
0                     289                               36            13   33   
1                     118                               13            18   50   
2                     179                               51            18   38   
3                     279                                5            14   39   
4                     289                               36            13   33   

   Work load Average/day   ...  Disciplinary failure  Education  Son  \
0                 239.554  ...                     0          1    2   
1                 239.554  ...                     1          1    1   
2                 239.554  ...                     0          1    0   
3                 239.554  ...                     0          1    2   
4                 239.554  ...                     0          1    2   

   Social drinker  Social smoker  Pet  Weight  Height  Body mass index  \
0               1              0    1      90     172               30   
1               1              0    0      98     178               31   
2               1              0    0      89     170               31   
3               1              1    0      68     168               24   
4               1              0    1      90     172               30   

   Absenteeism time in hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2  

[5 rows x 21 columns]

In [65]:
a_at_w = a_at_w.drop('ID',axis=1)

In [66]:
a_at_w.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 20 columns):
Reason for absence                 740 non-null int64
Month of absence                   740 non-null int64
Day of the week                    740 non-null int64
Seasons                            740 non-null int64
Transportation expense             740 non-null int64
Distance from Residence to Work    740 non-null int64
Service time                       740 non-null int64
Age                                740 non-null int64
Work load Average/day              740 non-null float64
Hit target                         740 non-null int64
Disciplinary failure               740 non-null int64
Education                          740 non-null int64
Son                                740 non-null int64
Social drinker                     740 non-null int64
Social smoker                      740 non-null int64
Pet                                740 non-null int64
Weight                       

In [67]:
a_at_w.describe()

Reason for absence  Month of absence  Day of the week     Seasons  \
count          740.000000        740.000000       740.000000  740.000000   
mean            19.216216          6.324324         3.914865    2.544595   
std              8.433406          3.436287         1.421675    1.111831   
min              0.000000          0.000000         2.000000    1.000000   
25%             13.000000          3.000000         3.000000    2.000000   
50%             23.000000          6.000000         4.000000    3.000000   
75%             26.000000          9.000000         5.000000    4.000000   
max             28.000000         12.000000         6.000000    4.000000   

       Transportation expense  Distance from Residence to Work  Service time  \
count              740.000000                       740.000000    740.000000   
mean               221.329730                        29.631081     12.554054   
std                 66.952223                        14.836788      4.384873   
min                118.000000                         5.000000      1.000000   
25%                179.000000                        16.000000      9.000000   
50%                225.000000                        26.000000     13.000000   
75%                260.000000                        50.000000     16.000000   
max                388.000000                        52.000000     29.000000   

              Age  Work load Average/day   Hit target  Disciplinary failure  \
count  740.000000              740.000000  740.000000            740.000000   
mean    36.450000              271.490235   94.587838              0.054054   
std      6.478772               39.058116    3.779313              0.226277   
min     27.000000              205.917000   81.000000              0.000000   
25%     31.000000              244.387000   93.000000              0.000000   
50%     37.000000              264.249000   95.000000              0.000000   
75%     40.000000              294.217000   97.000000              0.000000   
max     58.000000              378.884000  100.000000              1.000000   

        Education         Son  Social drinker  Social smoker         Pet  \
count  740.000000  740.000000      740.000000     740.000000  740.000000   
mean     1.291892    1.018919        0.567568       0.072973    0.745946   
std      0.673238    1.098489        0.495749       0.260268    1.318258   
min      1.000000    0.000000        0.000000       0.000000    0.000000   
25%      1.000000    0.000000        0.000000       0.000000    0.000000   
50%      1.000000    1.000000        1.000000       0.000000    0.000000   
75%      1.000000    2.000000        1.000000       0.000000    1.000000   
max      4.000000    4.000000        1.000000       1.000000    8.000000   

           Weight      Height  Body mass index  Absenteeism time in hours  
count  740.000000  740.000000       740.000000                 740.000000  
mean    79.035135  172.114865        26.677027                   6.924324  
std     12.883211    6.034995         4.285452                  13.330998  
min     56.000000  163.000000        19.000000                   0.000000  
25%     69.000000  169.000000        24.000000                   2.000000  
50%     83.000000  170.000000        25.000000                   3.000000  
75%     89.000000  172.000000        31.000000                   8.000000  
max    108.000000  196.000000        38.000000                 120.000000

# We are going to check and see how many options employees are claiming for their absence.

In [93]:
print("Total Count of Reasons for Absenteeism: %s " %(a_at_w['Reason for absence'].value_counts().count()))

Total Count of Reasons for Absenteeism: 28 


### KNN requires scaled values, we will alter the datapoints in the following cells.

In [68]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [69]:
scaler.fit(a_at_w.drop('Reason for absence',axis=1))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [70]:
scaled_features = scaler.transform(a_at_w.drop('Reason for absence',axis=1))

In [74]:
df_feat = pd.DataFrame(scaled_features,columns=a_at_w.columns[1:])

In [95]:
df_feat.shape

(740, 19)

In [75]:
df_feat.head()

Month of absence  Day of the week   Seasons  Transportation expense  \
0          0.196763        -0.643947 -1.390175                1.011408   
1          0.196763        -0.643947 -1.390175               -1.544379   
2          0.196763         0.059924 -1.390175               -0.632665   
3          0.196763         0.763796 -1.390175                0.861947   
4          0.196763         0.763796 -1.390175                1.011408   

   Distance from Residence to Work  Service time       Age  \
0                         0.429556      0.101770 -0.532868   
1                        -1.121694      1.242825  2.092860   
2                         1.441240      1.242825  0.239405   
3                        -1.661258      0.329981  0.393859   
4                         0.429556      0.101770 -0.532868   

   Work load Average/day   Hit target  Disciplinary failure  Education  \
0               -0.818212    0.638686             -0.239046  -0.433857   
1               -0.818212    0.638686              4.183300  -0.433857   
2               -0.818212    0.638686             -0.239046  -0.433857   
3               -0.818212    0.638686             -0.239046  -0.433857   
4               -0.818212    0.638686             -0.239046  -0.433857   

        Son  Social drinker  Social smoker      Pet    Weight    Height  \
0  0.893723        0.872872      -0.280566  0.19285  0.851673 -0.019046   
1 -0.017234        0.872872      -0.280566 -0.56624  1.473056  0.975828   
2 -0.928191        0.872872      -0.280566 -0.56624  0.774000 -0.350671   
3  0.893723        0.872872       3.564226 -0.56624 -0.857131 -0.682295   
4  0.893723        0.872872      -0.280566  0.19285  0.851673 -0.019046   

   Body mass index  Absenteeism time in hours  
0         0.775932                  -0.219511  
1         1.009438                  -0.519767  
2         1.009438                  -0.369639  
3        -0.625100                  -0.219511  
4         0.775932                  -0.369639

In [76]:
from sklearn.model_selection import train_test_split

In [77]:
X = df_feat
y = a_at_w['Reason for absence']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.27, random_state=47)

# K = 4
##### This is just to make sure the algorithm is performing

In [83]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix
knn = KNeighborsClassifier(n_neighbors=4)

In [84]:
knn.fit(X_train,y_train)
pred = knn.predict(X_test)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[ 7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  1  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  1  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  1  1  0  0  1  0  0]
 [ 0  2  0  0  0  2  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  2  3  0  3  0  0  0  0  0  0  2  0  0  0  3  2]
 [ 0  1  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  1  0  1]
 [ 0  0  0  0  0  0  0  0

/anaconda3/envs/DataScience/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/envs/DataScience/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/anaconda3/envs/DataScience/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/envs/DataScience/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true',

# Obviously, the low K is not going to have any actual success predicting 28 potential classes. Now we will up the K amount and see how well the model begins to perform. 

# K = 25

In [85]:
knn = KNeighborsClassifier(n_neighbors=25)
knn.fit(X_train,y_train)
pred = knn.predict(X_test)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[ 8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  2  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0  2  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  1  6  0  0  0  4  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  2  0  1  0

/anaconda3/envs/DataScience/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/envs/DataScience/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/envs/DataScience/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# It appears to only have increased accuracy slightly. Perhaps the data is generally unique per individual enough that the algorithm has a difficutl time sifting through it. 

# Lets try one last time. After all, third time's the charm.  
# K = 28

In [94]:
knn = KNeighborsClassifier(n_neighbors=28)
knn.fit(X_train,y_train)
pred = knn.predict(X_test)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[ 8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0  2  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  7  0  0  0  4  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  4  0  1  0

/anaconda3/envs/DataScience/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/envs/DataScience/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/envs/DataScience/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# This test made the test worse. I would be willing to say this dataset is not excellent for this form of data.